# Generated by Django 6.0.2 on 2026-02-23 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='applications/')),
                ('active', models.IntegerField(choices=[(0, 'unseen'), (1, 'in_progress'), (2, 'approved')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'complaint'), (1, 'reception'), (2, 'doctor')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
