# Generated by Django 6.0.2 on 2026-02-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active_account',
        ),
    ]
