# Generated by Django 6.0.2 on 2026-02-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_active_account'),
        ('hospitals', '0002_alter_hospital_director'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
    ]
